version: "3"

services:
  database:
    image: postgres:alpine
    env_file: .env
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./db/changelog/master/001-init-schema.sql:/docker-entrypoint-initdb.d/init.sql
      - db:/var/lib/postgresql/data

  server:
    build:
      context: .
      dockerfile: Dockerfile
    image: flappy-service
    env_file: .env
    volumes:
      - ./logs:/logs
    depends_on:
      - database
    ports:
      - "8080:8080"
    links:
      - database
    restart: always

volumes:
  db: